Repository CS2113-AY1819S1-T09-2/main, pull requests merged in 2018-11, with the labels that each got.

#86 bug fix for ET_check
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/arty9.adoc
  src/main/java/seedu/address/logic/commands/CheckExpenditureCommand.java
  src/main/java/seedu/address/model/expenditureinfo/Date.java
  src/test/java/seedu/address/testutil/TypicalExpenditures.java
Labels: type.bug, type.documentations

#115 [Expenditure Tracker] ET_advice popup window update
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/commands/PopUpAdvice.java
Labels: type.task

#116 bug fixes from PE1
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/UndoableCommandHistory.java
  src/main/java/seedu/address/logic/commands/CheckExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/UncompleteTaskCommand.java
  src/main/java/seedu/address/model/expenditureinfo/Category.java
  src/main/java/seedu/address/model/expenditureinfo/Date.java
  src/main/java/seedu/address/model/expenditureinfo/Expenditure.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/test/java/seedu/address/model/task/TaskDateTest.java
Labels: type.documentations, type.task

#119 check command update
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/commands/PopUpString.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/model/ExpenditureTracker.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/expenditureinfo/ExpenditureList.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.task

#121 Bug fix for ET_advice
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/parser/ExpenditureGetAdviceCommandParser.java
  src/main/java/seedu/address/model/CalendarInfo.java
  src/main/java/seedu/address/model/expenditureinfo/Money.java
  src/test/java/seedu/address/model/expenditureinfo/MoneyTest.java
Labels: type.task

#130 docs changes
  build.gradle
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/templates/_header.html.slim
Labels: type.documentations

#131 docs changes
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/templates/_header.html.slim
Labels: type.documentations

#135 collate tagging
  docs/UserGuide.adoc
  docs/team/arty9.adoc
  src/main/java/seedu/address/commons/events/model/TodoListChangedEvent.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UncompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UncompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewTaskCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyTodoList.java
  src/main/java/seedu/address/model/VersionedTodoList.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/main/java/seedu/address/model/task/TaskModule.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/TodoListStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlSerializableTodoList.java
  src/main/java/seedu/address/storage/XmlTodoListStorage.java
  src/test/java/seedu/address/model/TodoListTest.java
  src/test/java/seedu/address/model/VersionedTodoListTest.java
  src/test/java/seedu/address/model/task/TaskDateTest.java
  src/test/java/seedu/address/model/task/TaskModuleTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/XmlSerializableTodoListTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TodoListBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.documentations

#137 [Expenditure Tracker] test files update
  src/test/data/XmlSerializableExpenditureTrackerTest/duplicateExpenditureExpenditureTracker.xml
  src/test/data/XmlSerializableExpenditureTrackerTest/invalidExpenditureExpenditureTracker.xml
  src/test/data/XmlSerializableExpenditureTrackerTest/typical.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ExpenditureTrackerTest.java
  src/test/java/seedu/address/model/VersionedExpenditureTrackerTest.java
  src/test/java/seedu/address/storage/XmlSerializableExpenditureTrackerTest.java
Labels: type.task

#142 DG changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CompleteUncompleteTaskSequenceDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ViewTaskSequenceDiagram.pptx
  docs/images/CompleteUncompleteTaskSequenceDiagram.png
  docs/images/DeletePersonSdForLogic.png
  docs/images/DeleteTaskSdForLogic.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/SDforDeleteTask.png
  docs/images/SDforDeleteTaskEventHandling.png
  docs/images/ViewTaskSequenceDiagram.png
Labels: status.ongoing, type.documentations

#147 docs changes
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiClassDiagram.png
  docs/team/arty9.adoc
Labels: type.documentations

#153 docs cleanup
  docs/UserGuide.adoc
  docs/team/arty9.adoc
Labels: type.documentations

#157 test files + PPP
  docs/team/arty9.adoc
  src/main/java/seedu/address/logic/parser/CheckExpenditureCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/data/XmlTodoListStorageTest/NotXmlFormatTodoList.xml
  src/test/data/XmlTodoListStorageTest/invalidAndValidTaskTodoList.xml
  src/test/data/XmlTodoListStorageTest/invalidTaskTodoList.xml
  src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/address/storage/XmlTodoListStorageTest.java
Labels: type.documentations, type.task

#163 UGDG + PPP updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/arty9.adoc
Labels: type.documentations

#164 bug fix
  docs/stylesheets/asciidoctor.css
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
Labels: type.bug
