Repository CS2113-AY1819S1-T09-2/main, pull requests merged in 2018-10, with the labels that each got.

#3 [v1.1] added Task and related classes
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/main/java/seedu/address/model/task/TaskModule.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/task/TaskPriority.java
Labels: status.ongoing

#5 ported DG from google docs
  docs/DeveloperGuide.adoc
Labels: priority.high, status.ongoing

#8 docs fix for travis
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.ongoing, type.documentations

#9 more travis fixes: mostly syntax checkstyle errors
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ExpenditureTracker.java
  src/main/java/seedu/address/model/expenditureInfo/Date.java
  src/main/java/seedu/address/model/expenditureInfo/ExpenditureInfo.java
  src/main/java/seedu/address/model/expenditureInfo/Money.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: status.ongoing

#20 Model classes for Todo List
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/ReadOnlyTodoList.java
  src/main/java/seedu/address/model/TodoList.java
  src/main/java/seedu/address/model/VersionedTodoList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/main/java/seedu/address/model/task/TaskModule.java
  src/main/java/seedu/address/model/task/TaskPriority.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/test/java/seedu/address/model/TodoListTest.java
  src/test/java/seedu/address/model/VersionedTodoListTest.java
  src/test/java/seedu/address/model/task/TaskDateTest.java
  src/test/java/seedu/address/model/task/TaskModuleTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: priority.high, type.task

#24 Storage classes for TDL
  docs/AboutUs.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/TodoListChangedEvent.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TodoListStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableTodoList.java
  src/main/java/seedu/address/storage/XmlTodoListStorage.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TodoListBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.task

#48 documentation & diagram changes
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.bug, type.documentations

#52 UI changes and Complete/Uncomplete task commands
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UncompleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UncompleteTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/ExpenditureListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: type.task

#61 updated UG DG for v1.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CompleteUncompleteTaskSequenceDiagram.pptx
  docs/images/CompleteUncompleteTaskSequenceDiagram.png
Labels: type.documentations

#65 [Expenditure Tracker] Model update
  src/main/java/seedu/address/logic/commands/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ReadOnlyExpenditureTracker.java
  src/main/java/seedu/address/model/expenditureinfo/Category.java
  src/main/java/seedu/address/model/expenditureinfo/Description.java
  src/main/java/seedu/address/model/expenditureinfo/Expenditure.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedExpenditure.java
  src/main/java/seedu/address/ui/ExpenditureCard.java
  src/main/resources/view/ExpenditureListCard.fxml
  src/test/java/seedu/address/model/expenditureinfo/CategoryTest.java
  src/test/java/seedu/address/testutil/ExpenditureBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenditures.java
Labels: type.task

#66 [Expenditure Tracker] Do not recognise e/description
  src/main/java/seedu/address/logic/commands/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.task

#67 Partial RepoSense code matching update
  src/main/java/seedu/address/commons/events/model/ExpenditureTrackerChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/ExpenditurePanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/model/ExpenditureTracker.java
  src/main/java/seedu/address/model/ReadOnlyExpenditureTracker.java
  src/main/java/seedu/address/model/VersionedExpenditureTracker.java
  src/main/java/seedu/address/model/expenditureinfo/Category.java
  src/main/java/seedu/address/model/expenditureinfo/Date.java
  src/main/java/seedu/address/model/expenditureinfo/Description.java
  src/main/java/seedu/address/model/expenditureinfo/Expenditure.java
  src/main/java/seedu/address/model/expenditureinfo/ExpenditureList.java
  src/main/java/seedu/address/model/expenditureinfo/Money.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ExpenditureTrackerStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedExpenditure.java
  src/main/java/seedu/address/storage/XmlExpenditureTrackerStorage.java
  src/main/java/seedu/address/storage/XmlSerializableExpenditureTracker.java
  src/main/java/seedu/address/ui/ExpenditureCard.java
  src/main/java/seedu/address/ui/ExpenditureListPanel.java
  src/main/resources/view/ExpenditureListCard.fxml
  src/main/resources/view/ExpenditureListPanel.fxml
  src/test/java/seedu/address/model/expenditureinfo/CategoryTest.java
  src/test/java/seedu/address/model/expenditureinfo/DateTest.java
  src/test/java/seedu/address/model/expenditureinfo/ExpenditureListTest.java
  src/test/java/seedu/address/model/expenditureinfo/ExpenditureTest.java
  src/test/java/seedu/address/model/expenditureinfo/MoneyTest.java
  src/test/java/seedu/address/testutil/ExpenditureBuilder.java
  src/test/java/seedu/address/testutil/ExpenditureTrackerBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenditures.java
Labels: type.documentations

#68 Updates to Model, Storage and tests
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/VersionedExpenditureTracker.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.documentations, type.task

#70 View/Filter Task command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
Labels: status.ongoing, type.task

#69 [Expenditure Tracker] GetAdviceCommand update
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenditureCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExpenditureGetAdviceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ExpenditureTracker.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/expenditureinfo/ExpenditureList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExpenditureGetAdviceCommandTest.java
  src/test/java/seedu/address/model/expenditureinfo/DescriptionTest.java
  src/test/java/seedu/address/model/expenditureinfo/ExpenditureListTest.java
Labels: type.task

#75 UG update, ET_commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ViewExpenditureCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewExpenditureCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.task

#79 fix typo
  docs/UserGuide.adoc
Labels: type.documentations

#80 Various changes
  src/main/java/seedu/address/logic/commands/AddExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CheckExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewExpenditureCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/SortTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskDate.java
  src/main/java/seedu/address/model/task/TaskModule.java
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSerializableTodoListTest/duplicateTaskTodoList.xml
  src/test/data/XmlSerializableTodoListTest/invalidTaskTodoList.xml
  src/test/data/XmlSerializableTodoListTest/typicalTasksTodoList.xml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/TodoListTest.java
  src/test/java/seedu/address/model/VersionedTodoListTest.java
  src/test/java/seedu/address/model/task/TaskDateTest.java
  src/test/java/seedu/address/model/task/TaskPriorityTest.java
  src/test/java/seedu/address/storage/XmlSerializableTodoListTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.task

#81 More changes for v1.3 release
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExpenditureGetAdviceCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.ongoing, type.documentations, type.task

#83 Calendar UI update, ET_advice bug fix
  src/main/java/seedu/address/model/CalendarInfo.java
  src/main/java/seedu/address/model/expenditureinfo/ExpenditureList.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.bug, type.task

#84 ET_check command logic fix
  src/main/java/seedu/address/logic/commands/CheckExpenditureCommand.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.bug
